language: python
python:
  - "3.8.2"

install:  # command to install dependencies
  - pip install -r requirements.txt

script:  # command to run tests
  - python -m unittest tests.test_fundamental_analysis