from datetime import datetime
from pprint import pprint

import numpy as np

import data_scraping.financial_data_scraper as scraper

dictio = {
    'CONSOLIDATED STATEMENTS OF CASH FLOWS': {'Cash, cash equivalents and restricted cash, beginning balances': 25913.0,
                                              'Operating activities_Net income': 55256.0,
                                              'Operating activities_Adjustments to reconcile net income to cash generated by operating activities_Depreciation and amortization': 12547.0,
                                              'Operating activities_Adjustments to reconcile net income to cash generated by operating activities_Share-based compensation expense': 6068.0,
                                              'Operating activities_Adjustments to reconcile net income to cash generated by operating activities_Deferred income tax expense/(benefit)': -340.0,
                                              'Operating activities_Adjustments to reconcile net income to cash generated by operating activities_Deferred income tax expense/(benefit)_Other': -652.0,
                                              'Operating activities_Changes in operating assets and liabilities_Accounts receivable, net': 245.0,
                                              'Operating activities_Changes in operating assets and liabilities_Inventories': -289.0,
                                              'Operating activities_Changes in operating assets and liabilities_Vendor non-trade receivables': 2931.0,
                                              'Operating activities_Changes in operating assets and liabilities_Other current and non-current assets': 873.0,
                                              'Operating activities_Changes in operating assets and liabilities_Accounts payable': -1923.0,
                                              'Operating activities_Changes in operating assets and liabilities_Deferred revenue': -625.0,
                                              'Operating activities_Changes in operating assets and liabilities_Other current and non-current liabilities': -4700.0,
                                              'Operating activities_Changes in operating assets and liabilities_Other current and non-current liabilities_Cash generated by operating activities': 69391.0,
                                              'Investing activities_Purchases of marketable securities': -39630.0,
                                              'Investing activities_Proceeds from maturities of marketable securities': 40102.0,
                                              'Investing activities_Proceeds from sales of marketable securities': 56988.0,
                                              'Investing activities_Payments for acquisition of property, plant and equipment': -10495.0,
                                              'Investing activities_Payments made in connection with business acquisitions, net': -624.0,
                                              'Investing activities_Purchases of non-marketable securities': -1001.0,
                                              'Investing activities_Proceeds from non-marketable securities': 1634.0,
                                              'Investing activities_Other': -1078.0,
                                              'Investing activities_Other_Cash generated by/(used in) investing activities': 45896.0,
                                              'Financing activities_Proceeds from issuance of common stock': 781.0,
                                              'Financing activities_Payments for taxes related to net share settlement of equity awards': -2817.0,
                                              'Financing activities_Payments for dividends and dividend equivalents': -14119.0,
                                              'Financing activities_Repurchases of common stock': -66897.0,
                                              'Financing activities_Proceeds from issuance of term debt, net': 6963.0,
                                              'Financing activities_Repayments of term debt': -8805.0,
                                              'Proceeds from/(Repayments of) commercial paper, net': -5977.0,
                                              'Proceeds from/(Repayments of) commercial paper, net_Other': -105.0,
                                              'Proceeds from/(Repayments of) commercial paper, net_Other_Cash used in financing activities': -90976.0,
                                              'Increase/(Decrease) in cash, cash equivalents and restricted cash': 24311.0,
                                              'Increase/(Decrease) in cash, cash equivalents and restricted cash_Cash, cash equivalents and restricted cash, ending balances': 50224.0,
                                              'Increase/(Decrease) in cash, cash equivalents and restricted cash_Supplemental cash flow disclosure_Cash paid for income taxes, net': 15263.0,
                                              'Increase/(Decrease) in cash, cash equivalents and restricted cash_Supplemental cash flow disclosure_Cash paid for interest': 3423.0}}
visited_data_names = {}
year = datetime(2019, 9, 28)
pprint(scraper.normalize_tables(dictio, visited_data_names, year))